apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: inventory-api
  namespace: demo-inventory-app
  labels:
    app: inventory-api
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      referencePolicy:
        type: Local
